### ISSUE TITLE
BreadcrumbsItem cannot work with Jest

### ISSUE THREAD

**Issue by yuhong-l** [oklas/react-breadcrumbs-dynamic#24]
When using JEST, a exception will be thrown if <BreadcrumbsItem /> is used.

class xx {
render (){
return (
<BreadcrumbsItem key="1" to="/test/tt">
                    test</BreadcrumbsItem>
);
}
}

 TypeError: Cannot read property 'add' of undefined
      at node_modules/react-through/lib/throughAgent.js:103:42
          at Array.forEach (<anonymous>)
      at ThroughAgent._this.update (node_modules/react-through/lib/throughAgent.js:101:15)
      at Object.ThroughAgent._this.item (node_modules/react-through/lib/throughAgent.js:74:17)
      at ThroughAgent._this.configureItem.notused [as configureItem] (node_modules/react-through/lib/throughAgentFactory
.js:75:21)
      at ThroughAgent.componentWillMount (node_modules/react-through/lib/throughAgentFactory.js:87:14)
      at callComponentWillMount (node_modules/react-dom/cjs/react-dom.development.js:11507:14)
      at mountClassInstance (node_modules/react-dom/cjs/react-dom.development.js:11590:5)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:13145:7)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:13824:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:15863:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:15902:24)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:15942:7)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16560:22)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:16482:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16454:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16354:5)
      at scheduleWork$1 (node_modules/react-dom/cjs/react-dom.development.js:16218:11)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:16785:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:16812:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:16839:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17122:3)
      at node_modules/react-dom/cjs/react-dom.development.js:17262:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:16679:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:17258:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:17317:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:218:50)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:130:16)
      at Object.mount (node_modules/enzyme/build/mount.js:21:10)
      at mountDocumentation (tests/xxx/Documentation/Documentation.test.tsx:28:23)
      at Object.beforeEach (tests/xxx/Documentation/Documentation.test.tsx:35:32)

**Comment by oklas** [comment]
Tests existes in the repo and they are working. Check is actually ThroughProvider is used at the root. Also provide react and jest versions.

**Comment by yuhong-l** [comment]
"babel-jest": "22.4.0",
 "jest": "22.4.0",
    "jest-css-modules": "1.1.0",
    "ts-jest": "22.4.6",
"react": "16.4.1",
    "react-breadcrumbs-dynamic": "1.0.15",
Thanks for you reply. :)
No sure it's Jest's problem or react-through/BreadcrumbsItem 's problem.
In my test, only component BreadcrumbsItem encounterred this issue.

**Comment by oklas** [comment]
As I said check is actually ThroughProvider is used at the root. The `through` may be undefined if there is no ThroughProvider at the top of react tree. May be you try to test your component isolated from whole app and therefore without ThroughProvider on top. I need to have access to some short and complete app that reproduces the problem for more detail check.

**Comment by oklas** [comment]
Also if your tests checks isolated component, in test environment you can mock `<BreadcrumbsItem>` with empty component or with mock component which check breadcrumbs props from tested component if you need to check it.

**Comment by oklas** [comment]
The component `<BreadcrumbsProvider>` is obsolete sinonym for `<ThroughProvider>`.  Use `<ThroughProvider>`.
